# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
# Dependencies
- script: sudo apt-get install xorg-dev libglu1-mesa-dev ninja-build
  displayName: Dependencies
# Git
# Initialize submodules
- script: | 
    git submodule init
    git submodule update
  displayName: Git Submodules
# CMake
# Build with the CMake cross-platform build system
- task: CMake@1
  inputs:
    cmakeArgs: "-GNinja .."
- script: |
    cd build
    ninja